### ISSUE TITLE
It's incompatble with baritone

### ISSUE THREAD

**Issue by Hudumannaia** [RubixDev/fabric-rug#21]
It's incompatble with baritone
some problem with pathfinding

part of log file related to it:
```
[16:54:03] [main/INFO]: [CHAT] [Baritone] Pathing exception: java.lang.NullPointerException
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: java.lang.NullPointerException
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.handler$bdi000$onGetHardness(class_4970.java:2557)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.lb.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.lb.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.lb.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.lb$$Lambda$7151/2114273220.apply(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.util.function.Function.lambda$compose$5(Function.java:68)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.util.function.Function$$Lambda$1189/819026549.apply(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.lb.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.hn.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.ir.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.hs.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.hr.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.hg.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.hh.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.em.a(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at baritone.em$$Lambda$7153/1872962795.run(Unknown Source)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:54:03] [pool-4-thread-4/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by RubixDev** [comment]
Didn't have time to work on it today anymore, so it will have to wait until next week

**Comment by RubixDev** [comment]
Would you be able to give more information on what versions of the mods you used, what other mods you had and when it occurs? I was not able to reproduce it myself yet

**Comment by RubixDev** [comment]
I am closing this due to inactivity

**Comment by Hudumannaia** [comment]
Oh yes, sorry. I play rare nowadays :/ i dont have time and i will start to
work soon.

RubixDev ***@***.***> ezt írta (időpont: 2021. júl. 15., Cs
21:20):
