### ISSUE TITLE
Not compatible with VillagerFix due to mixins on ZombieVillager

### ISSUE THREAD

**Issue by itsdinkd** [RubixDev/fabric-rug#32]
[04:01:44] [main/WARN]: @Redirect conflict. Skipping rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000, already redirected by villagerfix.mixins.json:ZombieEntityMixin->@Redirect::shouldConvert(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000
[04:01:44] [main/WARN]: @Redirect conflict. Skipping rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000, already redirected by villagerfix.mixins.json:ZombieEntityMixin->@Redirect::shouldConvert(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000
[04:01:44] [main/WARN]: @Redirect conflict. Skipping rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000, already redirected by villagerfix.mixins.json:ZombieEntityMixin->@Redirect::shouldConvert(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; with priority 1000
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.minecraft.class_1299.<clinit>(class_1299.java:178)
        at net.minecraft.class_3103.<clinit>(class_3103.java:28)
        at net.minecraft.class_3031.<clinit>(class_3031.java:80)
        at net.minecraft.class_5464.<clinit>(class_5464.java:184)
        at net.minecraft.class_5458.method_30571(class_5458.java:46)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:266)
        at net.minecraft.class_2966.method_12851(class_2966.java:44)
        at net.minecraft.server.Main.main(Main.java:92)
        ... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; in rug.mixins.json:ZombieEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap rug-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 36 more

**Comment by RubixDev** [comment]
Sorry for taking so long.

It looks like this got already fixed by lowering the priority on their end.
If not, you are welcome to re-open this issue.
